include: package:flutter_lints/flutter.yaml

linter:
  rules:
    file_names: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
