include: package:flutter_lints/flutter.yaml

# Overrides in place to not make huge diff, would be good to remove
# in the future
linter:
  rules:
    file_names: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
