name: carriage
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_sign_in: ^4.0.14
  http: ^0.12.0+2
  intl: ^0.16.1
  geolocation: ^1.1.2
  provider: ^4.0.5+1
  wakelock: ^0.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: SFPro
      fonts:
        - asset: fonts/SF-Pro-Text-Medium.ttf
  uses-material-design: true
  assets:
    - assets/images/


