name: carriage
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_sign_in: ^6.0.2
  http: ^0.13.0
  intl: ^0.18.0
  provider: ^6.0.5
  wakelock: ^0.6.2
  loading_overlay: ^0.3.0
  speech_bubble: ^0.0.9
  flutter_svg: ^2.0.4
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^8.0.0
  image_picker: ^0.8.4+1
  url_launcher:
  shared_preferences:
  firebase_messaging: ^14.4.0
  firebase_core:
  flutter_local_notifications:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.ttf
          weight: 900
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-Thin.ttf
          weight: 200
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 100
  uses-material-design: true
  assets:
    - assets/images/
