name: carriage
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_sign_in: ^4.0.14
  http: ^0.12.0+2
  intl: ^0.16.1
  geolocation: ^1.1.2
  provider: ^4.0.5+1
  wakelock: ^0.1.4+2
  loading_overlay: ^0.2.1
  speech_bubble: ^0.0.7
  flutter_svg: ^0.18.0
  jwt_decoder: ^1.0.3
  flutter_secure_storage: ^3.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: SFDisplay
      fonts:
        - asset: fonts/SFUIDisplay-Black.ttf
          weight: 900
        - asset: fonts/SFUIDisplay-Heavy.ttf
          weight: 800
        - asset: fonts/SFUIDisplay-Bold.ttf
          weight: 700
        - asset: fonts/SFUIDisplay-Semibold.ttf
          weight: 600
        - asset: fonts/SFUIDisplay-Medium.ttf
          weight: 500
        - asset: fonts/SFUIDisplay-Regular.ttf
          weight: 400
        - asset: fonts/SFUIDisplay-Light.ttf
          weight: 300
        - asset: fonts/SFUIDisplay-Thin.ttf
          weight: 200
        - asset: fonts/SFUIDisplay-Ultralight.ttf
          weight: 100
    - family: SFText
      fonts:
        - asset: fonts/SFUIText-Heavy.ttf
          weight: 800
        - asset: fonts/SFUIText-Bold.ttf
          weight: 700
        - asset: fonts/SFUIText-Semibold.ttf
          weight: 600
        - asset: fonts/SFUIText-Medium.ttf
          weight: 500
        - asset: fonts/SFUIText-Regular.ttf
          weight: 400
        - asset: fonts/SFUIText-Light.ttf
          weight: 300
  uses-material-design: true
  assets:
    - assets/images/


